M48
; DRILL file {KiCad 9.0.0} date 2025-03-23T20:19:00-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-23T20:19:00-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X131.0Y-31.5
X131.0Y-86.5
X179.0Y-31.5
X179.0Y-86.5
M30
